### ISSUE TITLE
nc-cms Cross Site Scripting

### ISSUE THREAD

**Issue by Marblue** [gnat/nc-cms#9]
Hello, I found that this cms may have some security problem 
you can edit your html on [http://localhost/nc-cms/nc-cms/index.php?action=edit_html&name=home_content](url)
and you can Input any evil js you want
<img width="887" alt="2018-10-15 3 14 00" src="https://user-images.githubusercontent.com/28978393/46921051-2ce14f00-d029-11e8-83b1-be16add3f153.png">
<img width="729" alt="2018-10-15 3 14 24" src="https://user-images.githubusercontent.com/28978393/46921053-2ce14f00-d029-11e8-9bfd-59e55cd9509e.png">
<img width="1089" alt="2018-10-15 3 14 51" src="https://user-images.githubusercontent.com/28978393/46921054-2d79e580-d029-11e8-9219-785bbea5086a.png">

**Comment by gnat** [comment]
@Marblue Are students simply being told to go around to projects including TinyMCE and open issues like these?

It's by design, my friend. Think about the security context here: The user would already need administrator privileges to access this form. If they want to add some javascript, they should be able to.

**Comment by gnat** [comment]
Closing, won't fix for reasons above.
